# -*- coding: utf-8 -*-
"""polimorfismo_parte3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gAE28M5JfIEUtyU4x2PLLQ75ncaoo6WG
"""

# Prof. Cloves Rocha
# Aula Prática: Herança e Polimorfismo
# Polimorfismo - Code 1
class Animal():
        def __init__(self, nome, peso):
          self.__nome = nome
          self.__peso = peso
        def __str__(self):
            return 'Nome: %s \nPeso: %f' % (self.__nome, self.peso)
        def __gt__(self, other):
            return self.__peso > other.__peso
        def __add__(self, other):
          return Animal(self.__nome + ', ' + other.__nome, self.__peso + other.__peso)
          
        def alimentar(self, comida):
              self.peso += comida
        
        @property
        def nome(self):
                return self.__nome
        @nome.setter
        def nome(self, new_name):
                  if type(new_name) == type(str()):
                          self.__nome = new_name

# Polimorfismo - Code 2 desenvolva o restante no desafio...
from Animal import Animal
 class Mamifero(Animal):
#Sobre o desafio, no Reino animal: principais características e classificações
#- Anfíbios.
#- Aves.
#- Mamíferos.
#- Peixes.
#- Répteis.

# Um exemplo simples de como seria uma classe Animal em Python:
class Animal:
    def __init__(self, name, species):
        self.name = name
        self.species = species
    
    def make_sound(self):
        print("O animal está fazendo um som.")
    
    def get_name(self):
        return self.name
    
    def get_species(self):
        return self.species

# Para criar um objeto da classe Animal em Python, podemos simplesmente instanciá-la da seguinte forma:
animal = Animal("Rex", "cachorro")

# Nesse exemplo, estamos criando um objeto animal da classe Animal com o nome "Rex" e a espécie "cachorro".

# Podemos então chamar os métodos da classe para interagir com o objeto. Por exemplo, para imprimir o nome do animal, podemos chamar o método get_name:
print(animal.get_name())  # saída: Rex

# E para fazer o animal emitir um som, podemos chamar o método make_sound:
animal.make_sound()  # saída: O animal está fazendo um som.
#Observe que a mensagem impressa no método make_sound é uma mensagem genérica e não específica para o objeto animal. Isso ocorre porque o método make_sound é definido na classe Animal e não na instância do objeto animal. Se desejarmos definir um som específico para o animal Rex, podemos criar uma subclasse de Animal e sobrescrever o método make_sound.