# -*- coding: utf-8 -*-
"""aula00.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/clovesrocha/ETE_LP/blob/main/aula00.ipynb
"""

# ETE CÍCERO DIAS
# DISCIPLINA: LP com Python
# PROFESSOR: CLOVES
# ESCREVE AQUI UM COMENTÁRIO
print('ESCREVA AQUI SEU CÓDIGO')

x = 2
print(type(x))

x = 'Olá mundo!'
print(x)
print(type(x))

x = 2 
y = 2
print(x == y)

x = 2**3
print(x)

x = 10//3 
print(x)

x = 10%3 
print(x)

aline = 3
bruna = 3
print(aline >= bruna)

media = 2
print(f'A média do estudante é: {media}.')

nome = input('Digite seu nome: ')
idade = input('Digite sua idade: ')
endereco = input('Digite seu endereço: ')
matricula = input('Digite sua matrícula:')
print(f'Seu nome é: {nome}.')
print(f'Sua idade é: {idade}.')
print(f'Seu endereco é: {endereco}.')
print(f'Sua matrícula é: {matricula}.')

nome = str(input('Digite seu nome: '))
print(f'Seu nome {nome}.')
print(type(nome))