# -*- coding: utf-8 -*-
"""Desafio_OO.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pMqF3AmDWOgZdeuMlK_8aJtpE-9lA8uo
"""

class Dispositivo:
  def __init__(self, tipo, modelo, ano):
    self.tipo = tipo
    self.modelo = modelo
    self.ano = ano

if __name__ == __main__:
  disp1 = Dispositivo("Celular", "Samsung", 2022)

import sqlite3

conn = sqlite3.connect()

def criarTabela():
  cursor = conn.cursor()
  conn.execute("""
  create table if not exists tarefa {
    cd_disp integer primary key autoincrement,
    disp text
    atualizado integer
  }""")

def adicionarDispositivo(disp):
  conn.execute("insert into disp(disp, atualizado) values (?, 0)", (disp))
  conn.commit()

def removerDispositivo(cd_disp):
  conn.execute("delete from disp where cd_disp = ?", (cd_disp))
  conn.commit()

def atualizarDispositivo(cd_disp):
  conn.execute("uptade disp set atualizado = 1 where cd_disp = ?", (cd_disp))
  conn.commit()

import db