# -*- coding: utf-8 -*-
"""LP_Desafio #1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-wSI8NQmZwd2dXGC7cS0JgPuMBlzLYH8
"""

#ETE Porto Digital
#Prof. Cloves Rocha
#LP_Subsequente_2022

class Professor:
 def __init__(self, nome_completo, matricula, origem, tipo, nivel_academico):
    self.nome_completo = nome_completo
    self.matricula = matricula
    self.origem = origem
    self.tipo = tipo
    self.nivel_dificuldade = nivel_dificuldade

cloves = Professor('Cloves A. da Rocha', '01', 'CIn UFPE', 'Academico', 'Mestrado')
print( cloves.nome_completo + "\n" + cloves.matricula + "\n" + "\n" + cloves.origem + "\n" + cloves.tipo + "\n" + "\n" + cloves.nivel_academico )

#ETE Porto Digital
#Prof. Cloves Rocha
#LP_Subsequente_2022.2
#Desafio #1

class Professor:
 def __init__(self, nome_completo, matricula, origem, tipo, nivel_academico):
    self.nome_completo = nome_completo
    self.matricula = matricula
    self.origem = origem
    self.tipo = tipo
    self.nivel_academico = nivel_academico

cloves = Professor('Cloves A. da Rocha', '01', 'CIn UFPE', 'Acadêmico', 'Mestrado')
print( cloves.nome_completo + "\n" + cloves.matricula + "\n" + "\n" + cloves.origem + "\n" + cloves.tipo + "\n" + "\n" + cloves.nivel_academico )